apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-inventario
  labels:
    app: gestor-inventario
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestor-inventario
  template:
    metadata:
      labels:
        app: gestor-inventario
    spec:
      containers:
      - name: gestor-inventario
        image: alexeyrueda823/gestor-inventario:829cb49785304cf739bb9b8cdd9d0846015adb27
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:wgoXCyBKImPioPBMXVTMIIpgjCcghMFn@shuttle.proxy.rlwy.net:28836/railway"
        - name: DJANGO_SETTINGS_MODULE
          value: "gestor_inventario.settings_production"
        - name: SECRET_KEY
          value: "production1234567890!@#$%^&*()_+"
        - name: LD_SDK_KEY
          value: "sdk-7f6eed98-6b82-4817-95b9-fa72610d4d54"
